### ISSUE TITLE
想请教一下打勾、打叉的图案如何生成的呢

### ISSUE THREAD

**Issue by liangjingdev** [MeYoung/Case_Minder_Vue#3]
![image](https://user-images.githubusercontent.com/25202438/139390998-00b7f70a-9183-42b1-b239-db9b7719b916.png)

**Comment by MeYoung** [comment]
二开， 新增的字段。  类似优先级的字段

**Comment by liangjingdev** [comment]
原来是新增的字段呀，楼主大大还会更新代码嘛，主要是不清楚那个图案咋贴上去的，前端的组件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 米阳 ***@***.***&gt;
发送时间: 2021年11月1日 10:50
收件人: MeYoung/Case_Minder_Vue ***@***.***&gt;
抄送: 梁竞 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[MeYoung/Case_Minder_Vue] 想请教一下打勾、打叉的图案如何生成的呢 (Issue #3)





 
二开， 新增的字段。  类似优先级的字段
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
